name: Automated Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose test target
        required: true
        default: test_create_customer
        type: choice
        options:
          - test_create_customer
          - test_sort_customer
          - test_delete

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox xvfb libdbus-glib-1-2 libgtk-3-0

      - name: Install latest Geckodriver
        run: |
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
          tar -xvzf geckodriver*.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest allure-pytest

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tests
        env:
          DISPLAY: ":99"
          MOZ_HEADLESS: 1
          MOZ_HEADLESS_WIDTH: 1920
          MOZ_HEADLESS_HEIGHT: 1080
        run: |
          case "${{ github.event.inputs.deployment_target }}" in
            test_create_customer)
              pytest test/test_add_customer.py -v --alluredir=allure-results
              ;;
            test_sort_customer)
              pytest test/test_sort_customer.py -v --alluredir=allure-results
              ;;
            test_delete_customer)
              pytest test/test_wdelete.py -v --alluredir=allure-results
              ;;
          esac

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results